"""Provenance: where did a value come from, and what depends on it.

Lineage walks the INFORMATION view backwards from an artifact:

    artifact ← PRODUCES ← event ← CONSUMES ← artifact ...
    artifact ← DERIVES_FROM (content containment) ← artifact
    artifact ← CONTAINS_ITEM ← list artifact (e.g. a retrieval result set)
    event    ← TRANSFERS ← event (memory write → read of the same key)

and annotates each event with its EXECUTION context (the CONTAINS chain it sits in), so
"generated by model call M, informed by retrieval R, inside planner P, in run U" can be
answered. Every step keeps the basis and confidence of the relation that justifies it.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from agentwatch.graph.traverse import Graph
from agentwatch.query.workspace import Workspace

INFO_BACK = {"PRODUCES", "CONSUMES", "DERIVES_FROM", "CONTAINS_ITEM", "TRANSFERS"}
TRANSFORM_KIND = {
    "MODEL_INVOCATION": "generation",
    "TOOL_INVOCATION": "tool transformation",
    "RETRIEVAL": "retrieval",
    "MEMORY_ACCESS": "memory transfer",
    "TRANSFORMATION": "transformation",
    "MESSAGE": "communication",
    "DELEGATION": "delegation",
    "STATE_MUTATION": "artifact production",
    "EXTERNAL_INPUT": "origin (external input)",
}


@dataclass
class LineageNode:
    node: str
    description: dict[str, Any]
    relation: str | None = None  # relation linking this node to its child in the tree
    basis: str | None = None
    confidence: float = 1.0
    context: list[dict[str, Any]] = field(default_factory=list)
    parents: list[LineageNode] = field(default_factory=list)
    truncated: bool = False
    repeat: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "node": self.node,
            "description": self.description,
            "relation": self.relation,
            "basis": self.basis,
            "confidence": self.confidence,
            "context": self.context,
            "truncated": self.truncated,
            "repeat": self.repeat,
            "parents": [p.to_dict() for p in self.parents],
        }


def _context(ws: Workspace, g: Graph, event_node: str, limit: int = 6) -> list[dict[str, Any]]:
    chain = []
    cur = event_node
    seen = {cur}
    for _ in range(limit):
        parents = g.parents(cur)
        if not parents:
            break
        cur = parents[0]
        if cur in seen:
            break
        seen.add(cur)
        chain.append(ws.describe_node(cur))
    return chain


def lineage(ws: Workspace, ref: str, *, max_depth: int = 12, run_id: str | None = None) -> dict[str, Any]:
    root_node = ws.resolve_node(ref)
    g = ws.graph(run_id)
    seen: set[str] = set()

    def build(node: str, depth: int, relation: str | None, basis: str | None, conf: float) -> LineageNode:
        desc = ws.describe_node(node)
        ln = LineageNode(node, desc, relation, basis, conf)
        if node.startswith("event:"):
            ln.context = _context(ws, g, node)
        if node in seen:
            ln.repeat = True
            return ln
        seen.add(node)
        if depth >= max_depth:
            ln.truncated = bool(g.inc.get(node))
            return ln
        for rel_id, nb in g.inc.get(node, []):
            rel = g.relations[rel_id]
            if rel["view"] != "INFORMATION" or rel["type"] not in INFO_BACK or nb.startswith("entity:"):
                continue
            ln.parents.append(build(nb, depth + 1, rel["type"], rel["basis"], rel["confidence"]))
        return ln

    tree = build(root_node, 0, None, None, 1.0)
    return {"root": tree.to_dict(), "metrics": metrics(tree), "node": root_node}


def dependents(ws: Workspace, ref: str, *, max_depth: int = 12, run_id: str | None = None) -> dict[str, Any]:
    """Forward lineage: later events and artifacts that depend on ``ref``."""
    node = ws.resolve_node(ref)
    g = ws.graph(run_id)
    steps = g.descendants(node, views=["INFORMATION"], types=INFO_BACK, max_depth=max_depth, skip_kinds=["entity"])
    out = []
    for s in steps:
        rel = g.relations[s.via] if s.via else {}
        out.append({**s.to_dict(), "description": ws.describe_node(s.node), "basis": rel.get("basis"), "confidence": rel.get("confidence")})
    return {"node": node, "dependents": out, "count": len(out),
            "affected_outputs": [d for d in out if d["node"].startswith("artifact:") and not g.out.get(d["node"])]}


def metrics(tree: LineageNode) -> dict[str, Any]:
    """Descriptive lineage metrics (EXPERIMENTAL; definitions in docs/v3/metrics/provenance.md)."""
    depth_max = 0
    transformations = 0
    origins: list[str] = []
    bases: dict[str, int] = {}
    min_conf = 1.0
    content_links = 0
    unsupported_candidates: list[str] = []

    def walk(n: LineageNode, depth: int, conf: float) -> None:
        nonlocal depth_max, transformations, min_conf, content_links
        depth_max = max(depth_max, depth)
        if n.basis:
            bases[n.basis] = bases.get(n.basis, 0) + 1
        if n.relation == "DERIVES_FROM":
            content_links += 1
        conf = min(conf, n.confidence)
        if n.description.get("type") == "event" and not n.repeat:
            transformations += 1
        if not n.parents and not n.repeat:
            origins.append(n.node)
            min_conf = min(min_conf, conf)
            if n.description.get("type") == "event" and not n.description.get("label", "").startswith(("EXTERNAL_INPUT", "RETRIEVAL")):
                unsupported_candidates.append(n.node)
        for p in n.parents:
            walk(p, depth + 1, conf)

    walk(tree, 0, 1.0)
    return {
        "provenance_depth": depth_max,
        "transformations": transformations,
        "origins": origins,
        "relations_by_basis": bases,
        "content_match_links": content_links,
        "weakest_path_confidence": round(min_conf, 3),
        "generated_without_traced_input": unsupported_candidates,
        "maturity": "EXPERIMENTAL",
    }


def render(result: dict[str, Any]) -> list[str]:
    """Plain-text lineage tree, root first, ancestors indented with ↑."""
    lines: list[str] = []

    def label(d: dict[str, Any]) -> str:
        if d["type"] == "artifact":
            return f"artifact {d['node'][9:21]} {d['label']!r}" if d.get("label") else f"artifact {d['node'][9:21]}"
        if d["type"] == "event":
            actor = f" by {d['actor']}" if d.get("actor") else ""
            return f"{d['label']}{actor} [{d['node'][6:14]}] {d['status']}"
        return d["label"]

    verbs = {"PRODUCES": "produced by", "CONSUMES": "input", "DERIVES_FROM": "derived from", "CONTAINS_ITEM": "item of",
             "TRANSFERS": "via memory from"}

    def walk(n: dict[str, Any], indent: int) -> None:
        pad = "  " * indent
        d = n["description"]
        if n["relation"] is None:
            lines.append(label(d))
        else:
            q = "" if n["basis"] == "DECLARED" else f"  ({n['basis'].lower()}, confidence {n['confidence']})"
            lines.append(f"{pad}↑ {verbs.get(n['relation'], n['relation'])} {label(d)}{q}{'  (see above)' if n['repeat'] else ''}")
        if d.get("type") == "event" and n["context"] and not n["repeat"]:
            ctx = " ← ".join(c["label"] for c in n["context"])
            lines.append(f"{pad}    within: {ctx}")
        if n.get("truncated"):
            lines.append(f"{pad}    … (depth limit)")
        for p in n["parents"]:
            walk(p, indent + 1)

    walk(result["root"], 0)
    return lines
